### ISSUE TITLE
Error on Launch 

### ISSUE THREAD

**Issue by autobotcoop** [zarroboogs/p4gpc.tinyfixes#1]
Directed over here from Reloaded. 
![p4gr2 crash](https://user-images.githubusercontent.com/39393574/90081925-60dc3880-dcc3-11ea-96dd-c211ba9b515c.jpg)

**Comment by zarroboogs** [comment]
This is most likely caused by using Reloaded II + p4gpc.modloader + p4gpc.tinyfixes (+ SpecialK) with the original non-hotfix Steam version (v2008), which was not built with the Large Address Aware flag and is therefore limited to 2 GiB of memory address space.

Make sure to either apply [this patch](https://ntcore.com/?page_id=371) to the executable or use one of the beta hotfix branches - all of which include executables built with the `/LAA` flag.
